Repository openshift/openshift-velero-plugin, pull requests merged in 2023-04, with the labels that each got.

#187 Bug 2174551 - Address CVE-2023-25173 with containerd upgrade
  go.mod
  go.sum
Labels: lgtm

#171 OADP-1075 Add annotation to exclude build pod volumes during backup
  go.mod
  go.sum
  velero-plugins/main.go
  velero-plugins/pod/backup.go
  velero-plugins/pod/backup_test.go
Labels: bugzilla/valid-bug, approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#191 oadp-1.1: OADP-1650 Add annotation to exclude build pod volumes during backup (#189)
  go.mod
  go.sum
  velero-plugins/main.go
  velero-plugins/pod/backup.go
  velero-plugins/pod/backup_test.go
Labels: approved, lgtm

#194 oadp-1.1: OADP-1650 Dynamic build pod volume exclude annotation
  velero-plugins/pod/backup.go
  velero-plugins/pod/backup_test.go
Labels: approved, lgtm
