Repository openshift/openshift-velero-plugin, pull requests merged in 2024-03, with the labels that each got.

#227 Upgrade to github.com/migtools/udistribution@v0.0.13-oadp-1.3
  go.mod
  go.sum
Labels: approved, lgtm

#228 OADP-3598 Dest NS Skip waiting for dockercfg secret if default SA do not need it.
  go.mod
  go.sum
  velero-plugins/clients/clients.go
  velero-plugins/common/shared.go
  velero-plugins/pod/restore.go
  velero-plugins/pod/restore_test.go
  velero-plugins/util/openshift/clusterversion.go
  velero-plugins/util/openshift/imageregistry.go
Labels: approved, lgtm

#236 OADP-3598: Update logic to wait for pull secret in pod restore plugin
  velero-plugins/pod/restore.go
  velero-plugins/util/openshift/imageregistry.go
Labels: approved, lgtm, jira/valid-reference

#231 OADP-3710: Fix pod restore plugin log
  velero-plugins/pod/restore.go
Labels: approved, jira/valid-reference

#239 OADP-3598 Check ImageRegistryConfig management state isn't set to Removed
  velero-plugins/pod/restore.go
  velero-plugins/util/openshift/imageregistry.go
Labels: approved, lgtm

#242 [OADP-1.3] Fix OADP-3654: fix CVE-2024-24786
  go.mod
  go.sum
Labels: approved, lgtm, jira/valid-reference
